name: defomstereo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch::pytorch=2.1.1
  - pytorch::torchvision=0.16.1
  - matplotlib
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - opt_einsum
  - imageio
  - scikit-image
  - p7zip
  - pip
  - pip:
    - gradio_imageslider
    - gradio==4.29.0
    - timm

